[theme]
base = "dark"
primaryColor = "#F39C12"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#303030"
textColor = "#E6E6E6"
font = "sans serif"

[server]
enableCORS = false
port = 8501

[global]
# Set the default layout for the app
layout = "centered"